#!/usr/bin/ruby
# encoding: utf-8

require_relative 'lib/tool'
require_relative 'lib/application'
require_relative 'lib/project_builder'
require 'rainbow'

def show_help
  puts "Usage: #{$0}\n\n"
  puts "  "+Rainbow("input/path/to/[HAMLFILE|XMLFILE]").bright+" => Build output files, from HAML/XML input file."
  puts "                                      Example: "+Rainbow($0+" input/foo/foo.haml").yellow
  puts "                                      Example: "+Rainbow($0+" input/foo/foo.xml").yellow
  puts "  "+Rainbow("--help, -h, help, h").bright+"              => Show this help."
  puts "  "+Rainbow("--version, -v, version, v").bright+"        => Show the program version."
  puts "\n\n"
  puts "  DEPRECATED:\n"
  puts "    "+Rainbow("--create PROJECTNAME").bright+"      => Create new FOO project."
  puts "                                 Example: "+Rainbow($0+" create foo").yellow
  puts "    "+Rainbow("project/path/to/YAMLFILE").bright+"  => Build output files from YAML config file."
  puts "                                 Example: "+Rainbow($0+" projects/foo/foo.yaml").yellow
  puts ""
end

def show_version
  app=Application.instance
  t = Rainbow(app.name).bright.blue+" (version "+Rainbow(app.version).green+")"
  puts t
end

if ARGV.count==0 then
  puts "Usage: "+Rainbow($0+" --help").yellow
elsif ['h','-h','help','--help'].include?(ARGV.first) then
  show_help
elsif ['v','-v','version','--version'].include?(ARGV[0]) then
  show_version
elsif ['c','-c','create','--create'].include?(ARGV[0]) then
  ProjectBuilder::create_project( ARGV[1], Application.instance.param[:inputbasedir])
else
  Tool.instance.run(ARGV.first)
end
