#!/usr/bin/ruby
# encoding: utf-8

require 'thor'

require 'rainbow'
require 'pry'
require_relative 'lib/tool'
require_relative 'lib/application'
require_relative 'lib/builder/project_builder'
require_relative 'lib/sinatra/sinatra_front_end'

class MyCLI < Thor

  desc "version", "show the program version"
  def version
    puts Rainbow(Application::name).bright.blue+" (version "+Rainbow(Application::version).green+")"
  end

  desc "web", "Run web editor"
  def web
    SinatraFrontEnd.run!
  end

  desc "file NAME", "Build output files, from HAML/XML input file."
  def file(name)
    Tool.new.start(name)
  end

  desc "create PROJECTNAME", "Create files for a new project"
  def create(projectname)
    ProjectBuilder::create_project( projectname )
  end

end

MyCLI.start(ARGV)

=begin
def show_help
  puts "Usage: #{$0}\n\n"
  puts "  "+Rainbow("input/path/to/[HAMLFILE|XMLFILE]").green+" => Build output files, from HAML/XML input file."
  puts "                                      Example: "+Rainbow($0+" input/foo/foo.haml").yellow
  puts "                                      Example: "+Rainbow($0+" input/foo/foo.xml").yellow
  puts "  "+Rainbow("--web, -w, web, w  ").green+"              => Init Web Editor."
  puts "  "+Rainbow("--help, -h, help, h").green+"              => Show this help."
  puts "  "+Rainbow("--version, -v, version, v").green+"        => Show the program version."
  puts "\n\n"
  puts "  DEPRECATED:\n"
  puts "    --create PROJECTNAME      => Create new FOO project."
  puts "                                 Example: #{$0} create foo"
  puts "    project/path/to/YAMLFILE  => Build output files from YAML config file."
  puts "                                 Example: #{$0} projects/foo/foo.yaml"
  puts ""
end
=end
