#!/usr/bin/ruby
# encoding: utf-8

require_relative 'lib/tool'
require_relative 'lib/application'
require 'rainbow'

def show_help
  puts "Usage: #{$0}\n\n"
  puts "\t"+Rainbow("--help").bright+"\t\t\t\tShow this help."
  puts "\t"+Rainbow("--version").bright+"\t\t\tShow the program version."
  puts "\t"+Rainbow("--create PROJECTNAME").bright+"\t\tCreate new FOO project."
  puts "\t\t\t\t\tExample: #{$0} create FOO"
  puts "\t"+Rainbow("path/to/project/YAMLFILE").bright+"\tBuild quiz and lesson data files, from YAML config file."
  puts "\t\t\t\t\tExample: #{$0} projects/foo/config.yaml"
  puts ""
end

def show_version
  app=Application.instance
  t = Rainbow(app.name).color(:green)+" (version "+Rainbow(app.version).color(:blue)+")"
  puts t
end

if ARGV.count==0 then
	puts "Usage: #{$0} --help"
elsif ['h','-h','help','--help'].include?(ARGV.first) then
	show_help
elsif ['v','-v','version','--version'].include?(ARGV[0]) then
	show_version
elsif ['c','-c','create','--create'].include?(ARGV[0]) then
	Tool.instance.create_project(ARGV[1])
else
	Tool.instance.run(ARGV.first)
end

__END__
%map{ :version => '1', :lang => 'en' }
  %concept
    %names concept1
    %context write,here,the,context,of,concept1
    %tags write,here,the,definition,of,the,concept1
    %text Write here the definition of [*]

  %concept
    %names concept2
    %context write,here,the,context,of,concept2
    %tags write,here,the,definition,of,the,concept2
    %table{ :fields => 'atrributename,value' }
      %title Attributes-values associated to concept2
      %row
        %col attributename1
        %col value of attributename1
      %row
        %col attributename1
        %col value of attributename2
      %row
        %col attributename1
        %col value of attributename3
