# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "asker-debian" do |i|
    i.vm.box = "generic/debian10"
    i.vm.hostname = "asker-debian"
#    i.vm.network "public_network", bridge: [ "eth1" ]
    i.vm.synced_folder "./", "/vagrant"
    i.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y ruby
      gem install asker-tool
      apt-get install -y git
      git clone https://github.com/dvarrui/asker-inputs
      chown -R vagrant:vagrant asker-inputs/
    SHELL

    i.vm.provider "virtualbox" do |v|
      v.name = 'asker-debian'
      v.memory = 2048
    end
  end
end
