# -*- mode: ruby -*-
# vi: set ft=ruby :

NAME="asker-debian"
BOXNAME= "generic/debian11"

Vagrant.configure("2") do |config|
  config.vm.define NAME do |i|
    i.vm.box = BOXNAME
    i.vm.hostname = NAME
    # i.vm.network "public_network", bridge: [ "eth0" ]
    # i.vm.network "public_network", bridge: [ "wlan0" ]
    i.vm.network :forwarded_port, guest: 22, host: 2241
    i.vm.synced_folder "./", "/vagrant"
    i.vm.provision "shell", inline: <<-SHELL
      apt update
      apt install -y vim tree nmap
      apt install -y ruby irb
      gem install asker-tool
      apt install -y git
      git clone https://github.com/dvarrui/asker-inputs
      chown -R vagrant:vagrant asker-inputs/
    SHELL

    i.vm.provider "virtualbox" do |v|
      v.name = NAME
      v.memory = 2048
    end
  end
end
