# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "asker-opensuse" do |i|
    # i.vm.box = "opensuse/openSUSE-15.0-x86_64"
    i.vm.box = "generic/opensuse15"
    i.vm.hostname = "asker-opensuse"
    # i.vm.network "public_network", bridge: [ "eth0" ]
    # i.vm.network "public_network", bridge: [ "wlan0" ]
    i.vm.network :forwarded_port, guest: 22, host: 2231
    i.vm.synced_folder "./", "/vagrant"
    i.vm.provision "shell", inline: <<-SHELL
    SHELL
    i.vm.provision "shell", inline: <<-SHELL
      zypper refresh
      zypper install -y vim tree nmap

      gem install asker-tool
      ln -s /usr/bin/asker.ruby2.5 /usr/local/bin/asker

      zypper install -y git
      git clone https://github.com/dvarrui/asker-inputs
      chown -R vagrant:vagrant asker-inputs/

      zypper install -y figlet
      figlet asker > /etc/motd
      echo "" >> /etc/motd
      echo "asker (2.2.0)" >> /etc/motd
      echo "https://github.com/dvarrui/asker" >> /etc/motd
      echo "" >> /etc/motd

      echo "# Adding more alias" >> /home/vagrant/.bashrc
      echo "alias c='clear'" >> /home/vagrant/.bashrc
      echo "alias v='vdir'" >> /home/vagrant/.bashrc
    SHELL
    i.vm.provider "virtualbox" do |v|
      v.name = 'asker-opensuse'
      v.memory = 2048
    end
  end
end
