#!/usr/bin/ruby
# encoding: utf-8

module LogActions

  def create_log_file
	app=Application.instance

    #create or reset logfile
    Dir.mkdir(app.outputdir) if !Dir.exists? app.outputdir

    @logfile=File.open(@logname,'w')
    @logfile.write("="*50+"\n")
    @logfile.write("Generated by #{app.name} (version #{app.version})\n")
    @logfile.write("File: #{@logname}\n")
    @logfile.write("Time: "+Time.new.to_s+"\n")
    @logfile.write("="*50+"\n")
  end

  def close_log_file
    @logfile.close
  end
end
